// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $articles from "./routes/articles.ts";
import * as $index from "./routes/index.tsx";
import * as $subscribe from "./routes/subscribe.ts";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
    routes: {
        "./routes/_404.tsx": $_404,
        "./routes/_app.tsx": $_app,
        "./routes/articles.ts": $articles,
        "./routes/index.tsx": $index,
        "./routes/subscribe.ts": $subscribe,
    },
    islands: {},
    baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
